In [ ]:
import torch
a = torch.ones(10, 3)
b = torch.ones(10)
c = [(a[i], b[i]) for i in range(len(a))]

In [4]:
import torch
def f(a):
    a[0] = a[0] + 1
a = torch.tensor([0])
for i in range(2):
    f(a)
print(a)

tensor([2])


In [7]:
import torch
a = torch.tensor(1)
float(a)

1.0

In [2]:
import numpy as np
is_poison = [0 for _ in range(40) ] + [1 for _ in range(5)]
is_poison = np.array(is_poison)
is_poison

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       1])

In [8]:
NB_POISON = 5
NB_DEVICES = 4
clean_prov = np.random.randint(NB_DEVICES - 1, size=40)
print(clean_prov)
p_train = np.eye(NB_DEVICES)[clean_prov]
p_train
# poison_prov = np.zeros((NB_POISON, NB_DEVICES))
# poison_prov[:, NB_DEVICES - 1] = 1
# all_p = np.vstack([p_train, poison_prov])
# all_p

[1 1 2 1 1 0 2 1 1 1 1 1 0 1 1 1 0 2 0 0 1 0 0 2 2 0 2 0 1 0 0 2 0 2 0 1 1
 0 0 1]


array([[0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.]])

In [6]:
a = np.array([0,1,0,1,0])
np.sum(a==0)

3

In [10]:
a = np.array([1,2])
b = np.array([3,4])
np.vstack((a, b))

array([[1, 2],
       [3, 4]])

In [3]:
assert False and False

AssertionError: 

In [11]:
[1] == 1

False

In [8]:
import numpy as np
a = np.array([[1, 2, 3], [1, 2, 3]])
print(a.shape)

(2, 3)


In [20]:
a = np.array([[1], [2], [3]])
a = np.array([1, 2, 3])
print(a.ravel())

[1 2 3]


In [2]:
def a():
    return 1, 2, 3
c, d, e = a()
print(c, d)

1 2


In [3]:
8. / 255

0.03137254901960784

In [9]:
import torchvision
import torch
from torchvision import datasets, transforms
import numpy as np
transform_test = transforms.Compose([transforms.ToTensor()])
testset = torchvision.datasets.CIFAR10(root='data/CIFAR10', train=True, download=True, transform=transform_test)
mean = np.mean(testset.data, axis=(0, 1, 2)) / 255
std = np.std(testset.data, axis=(0, 1, 2)) / 255
print(mean, std)
#[0.49139968 0.48215841 0.44653091] [0.24703223 0.24348513 0.26158784] train

Files already downloaded and verified
[0.49139968 0.48215841 0.44653091] [0.24703223 0.24348513 0.26158784]


In [19]:
import torch
import torchvision
import torchvision.transforms as transforms

# 读取MNIST数据集
train_dataset = torchvision.datasets.MNIST(root='data/MNIST/', train=True, download=True, transform=transforms.ToTensor())

# 计算均值和方差
mean = 0.
std = 0.
for images, _ in train_dataset:
    batch_samples = images.size(0) # 当前batch的图像数量
    images = images.view(batch_samples, images.size(1), -1)
    mean += images.mean(2).sum(0)
    std += images.std(2).sum(0)

mean /= len(train_dataset) * images.size(1)
std /= len(train_dataset) * images.size(1)

print("Mean: ", mean)
print("Std: ", std)


Mean:  tensor([6.8444e-08, 8.6997e-06, 1.4299e-04, 5.2522e-04, 1.8422e-03, 3.9757e-03,
        5.9242e-03, 7.2233e-03, 7.5670e-03, 7.1885e-03, 6.6448e-03, 6.4372e-03,
        6.6988e-03, 7.2088e-03, 7.6236e-03, 7.6431e-03, 7.2388e-03, 6.7188e-03,
        6.5202e-03, 6.7036e-03, 6.9646e-03, 6.8137e-03, 5.8608e-03, 4.1603e-03,
        2.0145e-03, 7.3185e-04, 2.5524e-04, 2.4181e-05])
Std:  tensor([2.5336e-07, 3.0355e-05, 4.4513e-04, 1.3600e-03, 4.1846e-03, 7.7976e-03,
        1.0431e-02, 1.2071e-02, 1.2412e-02, 1.2174e-02, 1.1923e-02, 1.1917e-02,
        1.2176e-02, 1.2510e-02, 1.2703e-02, 1.2620e-02, 1.2304e-02, 1.1939e-02,
        1.1755e-02, 1.1826e-02, 1.1989e-02, 1.1807e-02, 1.0681e-02, 8.5490e-03,
        4.8401e-03, 2.0762e-03, 7.9693e-04, 8.1013e-05])


In [21]:
import torch

list_of_tensors = [torch.tensor(1), torch.tensor(2), torch.tensor(3)]
tensor = torch.stack(list_of_tensors)
tensor

tensor([1, 2, 3])

In [26]:
import torch
a = torch.tensor([1.], requires_grad=True)
sourceTensor = torch.tensor([1.], requires_grad=True)
print(sourceTensor.clone().detach())
print(a.new_tensor(sourceTensor))

tensor([1.])
tensor([1.])


/mnt/data/miniconda3/envs/art/lib/python3.7/site-packages/ipykernel_launcher.py:5: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than tensor.new_tensor(sourceTensor).
  """


In [1]:
import os
import torch
from control.defense.models import *
from control.defense.preprocessor.preprocessor import *
os.environ["CUDA_VISIBLE_DEVICES"] = "0"
device = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")
if torch.cuda.is_available():
    print("got GPU")

# model = ResNet18()
# # checkpoint = torch.load('/mnt/data2/yxl/AI-platform/trades/model-cifar-wideResNet/model-wideres-epoch85.pt')
# checkpoint = torch.load('/mnt/data2/yxl/AI-platform/trades-clean/model-cifar-wideResNet/model-wideres-epoch85.pt')
# model.load_state_dict(checkpoint)
# model = model.to(device)   
mean = (0.1307,)
std = (0.3081,)
model = SmallCNN()
checkpoint = torch.load('/mnt/data2/yxl/AI-platform/trades-clean/model-mnist-smallCNN/model-nn-epoch61.pt')
model.load_state_dict(checkpoint)
model = model.to(device)
deflection = Pixel_defend(model = model, mean = mean, std = std, adv_method='PGD', adv_dataset='MNIST', adv_nums=100, device=device)
deflection.detect()
deflection.print_res()

/mnt/data/miniconda3/envs/art/lib/python3.7/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


got GPU


INFO:art.estimators.classification.pytorch:Inferred 1 hidden layers on PyTorch classifier.


accuracy: 1.0 robustness: 0.14999999105930328
bpda_robustness: 0.10999999940395355
detect rate:  0.17999999225139618


In [2]:
import numpy as np
a = np.load('adv_CIFAR10_PGD.npy')
print(a.shape)

(10000, 3, 32, 32)


In [4]:
TPR = 0.8  # 已知TPR
FPR = 0.2  # 已知FPR
P = 1000  # 已知正例总数
N = 0  # 已知反例总数

TP = TPR * P
FP = FPR * N
TN = N - FP
FN = P - TP

ACC = (TP + TN) / (P + N)
print(ACC)


0.8


In [2]:
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "0"
import numpy as np
import torch
# a = np.load('data/CIFAR10/adv_CIFAR10_PGD.npy')
a = np.load('data/MNIST/adv_MNIST_PGD.npy')
print(a.shape)
img = torch.from_numpy(a[0]).unsqueeze(0).cuda()
# Data


/mnt/data/miniconda3/envs/art/lib/python3.7/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


(10000, 1, 28, 28)


In [3]:
def transform(img, dataset='cifar'):
    # Data
    if dataset == 'mnist':
        mean = torch.Tensor([0.1307]).unsqueeze(1).expand_as(img[0, :, :, 0]).unsqueeze(2).expand_as(
            img[0]).unsqueeze(0).expand_as(img).cuda()
        std = torch.Tensor([0.3081]).unsqueeze(1).expand_as(img[0, :, :, 0]).unsqueeze(2).expand_as(
            img[0]).unsqueeze(0).expand_as(img).cuda()
    elif dataset == 'cifar':
        mean = torch.Tensor([0.485, 0.456, 0.406]).unsqueeze(1).expand_as(img[0, :, :, 0]).unsqueeze(2).expand_as(
            img[0]).unsqueeze(0).expand_as(img).cuda()
        std = torch.Tensor([0.229, 0.224, 0.225]).unsqueeze(1).expand_as(img[0, :, :, 0]).unsqueeze(2).expand_as(
            img[0]).unsqueeze(0).expand_as(img).cuda()
    else:
        raise "dataset is not supported"
    return (img - mean) / std
transform(img, 'mnist').shape

torch.Size([1, 1, 28, 28])

In [26]:
a = (123)
torch.tensor([a])

tensor([123])

In [27]:
import os

file_path = '/path/to/your/file.txt'
dir_path = os.path.dirname(file_path)
print(dir_path)


/path/to/your


In [9]:
mean = 0.1307
std = 0.3081
def transform(img, adv_dataset, mean, std):
    # Data
    if adv_dataset == 'MNIST':
        mean_ = torch.Tensor([mean]).unsqueeze(1).expand_as(img[0, :, :, 0]).unsqueeze(2).expand_as(
            img[0]).unsqueeze(0).expand_as(img).cuda()
        std_ = torch.Tensor([std]).unsqueeze(1).expand_as(img[0, :, :, 0]).unsqueeze(2).expand_as(
            img[0]).unsqueeze(0).expand_as(img).cuda()
    elif adv_dataset == 'CIFAR10':
        mean_ = torch.Tensor(mean).unsqueeze(1).expand_as(img[0, :, :, 0]).unsqueeze(2).expand_as(
            img[0]).unsqueeze(0).expand_as(img).cuda()
        std_ = torch.Tensor(std).unsqueeze(1).expand_as(img[0, :, :, 0]).unsqueeze(2).expand_as(
            img[0]).unsqueeze(0).expand_as(img).cuda()
    else:
        raise "dataset is not supported"
    return (img - mean_) / std_
transform(img, 'MNIST', mean, std).shape

torch.Size([1, 1, 28, 28])

: 

In [1]:
import numpy as np
import torch
from torch.autograd import Variable as V

ne = 3
m, n = 79, 164
G = np.random.rand(m, n).astype(np.float64)
w = np.random.rand(n, n).astype(np.float64)
z = -np.random.rand(n).astype(np.float64)

G = V(torch.from_numpy(G))
w = V(torch.from_numpy(w))
z = V(torch.from_numpy(z), requires_grad=True)
e, v = torch.symeig(torch.diag(2 * z - torch.sum(w, dim=1)) + w, eigenvectors=True, upper=False)
ssev = torch.sum(torch.pow(e[-ne:] * v[:, -ne:], 2), dim=1)
out = torch.sum(torch.matmul(G, ssev.reshape((n, 1))))
out.backward(z)
print(z.grad)

/mnt/data/miniconda3/envs/art/lib/python3.7/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
/mnt/data/miniconda3/envs/art/lib/python3.7/site-packages/ipykernel_launcher.py:14: UserWarning: torch.symeig is deprecated in favor of torch.linalg.eigh and will be removed in a future PyTorch release.
The default behavior has changed from using the upper triangular portion of the matrix by default to using the lower triangular portion.
L, _ = torch.symeig(A, upper=upper)
should be replaced with
L = torch.linalg.eigvalsh(A, UPLO='U' if upper else 'L')
and
L, V = torch.symeig(A, eigenvectors=True)
should be replaced with
L, V = torch.linalg.eigh(A, UPLO='U' if upper else 'L') (Triggered internally at  ../aten/src/ATen/native/BatchLinearAlgebra.cpp:2524.)
  


RuntimeError: Mismatch in shape: grad_output[0] has a shape of torch.Size([164]) and output[0] has a shape of torch.Size([]).

In [3]:
import torch
a = torch.tensor([[1, 2], [10, 5]])
print(torch.argmax(a, dim=1))

tensor([1, 0])


In [2]:
from decimal import Decimal
Decimal('1.23456').quantize(Decimal('0.000'))
Decimal('1.235')
Decimal(123).quantize(Decimal('0.000'))
Decimal('123.0')


Decimal('123.0')